version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    timezone: UCT
  open-pull-requests-limit: 99
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    timezone: UCT
  open-pull-requests-limit: 99
